services:
  db:
    image: postgres:18
    container_name: livros-db # Não é obrigatório, é conveniência, dando o nome ele fica fixo no que eu escolhi.
    restart: unless-stopped # Define o que o Docker faz quando o container morre. unless-stopped: reinicia sempre, exceto quando eu faço parar a mão.
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432" # 5432 do Windows está ocupada pelo seu PG17 (lado esquerdo) (poderia ser qualquer número)
    volumes:
      - pgdata:/var/lib/postgresql # "pgdata": nome poderia ser outro; "var/lib/postgresql": pasta dentro do container onde o Postgres grava os dados. (imagem oficial - Docker Hub)
    healthcheck: # É um teste que o Docker roda repetidamente para saber se o container está realmente funcionando, não só ligado.
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s # roda a cada 5s
      timeout: 5s # se travar mais que isso, conta como falha
      retries: 10 # 10 falhas seguidas = marca como unhealthy

  redis:
    image: redis:8-alpine
    container_name: livros-cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: livros-celery
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command:
      [
        "celery",
        "-A",
        "app.celery_app:celery_app",
        "worker",
        "-Q",
        "livros",
        "--loglevel=info",
      ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: livros-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: livros-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: livros-kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:29092

  app:
    build: .
    container_name: livros-api
    restart: unless-stopped
    ports:
      - "8000:8000" # "direita": porque é o que esta no command(aqui/Dockerfile); "esquerda": é porque estava livre no meu Windows, poderia ser qualquer outro.
    volumes:
      - .:/app # ".": pasta NO MEU WINDOWS (ONDE ESTÁ O DOCKER); "/app": pasta DENTRO do container
    env_file:
      - .env
    environment:
      - KAFKA_SERVER=kafka:29092
    depends_on: # segura o app até o db estar pronto de verdade. É a peça queusa o healthcheck.
      db:
        condition: service_healthy # usa essa informação para segurar a partida
      redis:
        condition: service_started
      kafka:
        condition: service_started
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

volumes:
  pgdata:
